# -*- coding: utf-8 -*-
"""clothes_classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a2Y16-X0Cz9PZVDOHeE59-pRat9oYEM0
"""

import tensorflow as tf
from tensorflow import keras
import numpy as np

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

from matplotlib import pyplot as plt
n=300
plt.imshow(x_train[n])
print(y_train[n])

clothes = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal',	'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

model = keras.Sequential([
    keras.layers.Flatten(input_shape = (28, 28)),
    keras.layers.Dense(units = 100, activation = 'swish'),
    keras.layers.Dense(units = 200, activation = 'swish'),
    keras.layers.Dense(units = 200, activation = 'swish'),
    keras.layers.Dense(units = 100, activation = 'swish'),
    keras.layers.Dense(units = 10, activation = 'softmax')
])

print(model.summary)

train_data = x_train / 255
train_label = y_train / 255

model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = 'accuracy')
history = model.fit(x_train, y_train, epochs = 20, verbose = 1)

plt.plot(history.history['loss'])

plt.plot(history.history['accuracy'])

test_loss, test_acc= model.evaluate(x_test, y_test)
print(test_acc)

n = 10

x_test[10].shape

n = 906

pred = model.predict(x_test)
print(clothes[np.argmax(pred[n])])
plt.imshow(x_test[n])